// Regular Expressions
// Edward Eldridge (G00337490)

package main

import (
	"fmt"       // For taking in user input (https://golang.org/pkg/fmt/)
	"math/rand" // For our RNG (https://golang.org/pkg/math/rand/)
	"time"      // For our rng (https://golang.org/pkg/time/)
)

// Function to generate random number within a range
// Adapted from (http://golangcookbook.blogspot.ie/2012/11/generate-random-number-in-given-range.html)
func random(min, max int) int {

	// Set a seed for our RNG using time in nano seconds
	rand.Seed(time.Now().Unix())

	// Return our random integer to our main function
	// where we can set it's parameters
	return rand.Intn(max-min) + min
}

// Function that takes a single string as an input
// and returns a random string from an array of strings
func ElizaResponse() string {

	// Variables
	var outputArray [3]string
	var userInput string
	var randomString string

	// Our random number generated by our random function
	randomNumber := random(0, 2)

	// Initlize our array
	outputArray[0] = "I’m not sure what you’re trying to say. Could you explain it to me?"
	outputArray[1] = "How does that make you feel?"
	outputArray[2] = "Why do you say that?"

	//Put the random string in our array into a variable called randomString
	outputArray[randomNumber] = randomString

	// Print our results
	fmt.Printf("%s", randomString)

	// Prompt user for input
	// Create new reader so we can read strings
	fmt.Println("Please enter a sentence: ")
	fmt.Scanf("%s", &userInput)
	fmt.Printf("%s", userInput)

	// Return the randomString
	return randomString
}

func main() {
	ElizaResponse()
}
